@echo off
echo remove the files generated by compiler
echo.

echo remove the build files
rd .\build /s/q
echo.
echo remove the debug files
rd .\debug /s/q
echo.
echo remove the dist files
rd .\dist /s/q
echo.

exit